main: com.cavetale.easter.EasterPlugin
name: Easter
version: 0.1
api-version: 1.13
description: Easter Plugin
author: StarTux
website: https://cavetale.com
depend: [Mirage, Dirty, GenericEvents]
softdepend: []
commands:
  easter:
    description: Easter Command
    permission: easter.admin
    permission-message: You do not have permission!
    usage: |-
      /easter reload - reload config
      /easter start - start new round
      /easter info - round info
      /easter tp <idx> - Warp to egg
      /easter hi - Highscore
  hi:
    description: Highscore
    permission: easter.hi
    usage: |-
      /hi
permissions:
  easter.admin:
    description: Use /easter
  easter.hi:
    description: Use /hi
