main: com.cavetale.easter.EasterPlugin
name: Easter
version: 0.1
api-version: 1.13
description: Easter Plugin
author: StarTux
website: https://cavetale.com
depend: [WorldEdit, Mytems, Core, Sidebar]
softdepend: []

commands:

  easter:
    description: Easter Command
    permission: easter.easter
    usage: |-
      /easter

  easteradmin:
    description: Easter Command
    permission: easter.admin
    usage: |-
      /easteradmin

permissions:

  easter.easter:
    description: Use /easter
    default: op

  easter.admin:
    description: Use /easteradmin
    default: op

  easter.hunt:
    description: Hunt easter eggs
    default: false